### ISSUE TITLE
The same file of rwl was not always received error information when use the function of 'detrend'

### ISSUE THREAD

**Issue by muxi1995** [OpenDendro/dplR#13]
Dear Professor, 
  when I use the function of 'detrend' in 'dplR' package to detrend the trend of tree ring width I received an error that is "In (function (y, y.name = "", make.plot = TRUE, method = c("Spline",  : Spline fit is not all positive". But when did the same process again this error did not occur and the chronology of the rwl file was without a negative value. I want to know whether the chronology is reliable. I also hope you can give me some suggestions to deal with the problem in a batch process. Thank you a lot in advance.

**Comment by AndyBunn** [comment]
after our email exchange, i understand that this has been resolved.
