### ISSUE TITLE
What is the warnings meaning  when we detrend rwl in dplR

### ISSUE THREAD

**Issue by muxi1995** [OpenDendro/dplR#14]
Dear Professor,
when I use the function of 'detrend' in 'dplR' package to detrend the trend of tree ring width I received a warning as follows:
'In (function (y, y.name = "", make.plot = TRUE, method = c("Spline",  ... :
  In raw series YR338W: Linear fit (backup of method=='ModNegExp') is not all positive. 
  Proceed with caution. 
  ARSTAN would tell you to plot that dirty dog at this point."
But when did the detrending process by using "Spline" for another rwl file I received a warning as the following:
  ' In (function (y, y.name = "", make.plot = TRUE, method = c("Spline",  ... :
  In raw series 93-59: Fits from method=='Spline' are not all positive. 
  Series will be detrended with method=='Mean'. 
  This might not be what you want. 
  ARSTAN would tell you to plot that dirty dog at this point. 
  Proceed with caution. '
The second time the warnings said that  ' Series will be detrended with method=='Mean'.  While it did not appear at the first time. So I want to learn how it is processed the first time. I also read the source code of 'detrend'. But I am not sure whether it was also detrended with the method of 'Mean', except for "Ar". If I used the method of 'Ar' how does it process when the warning appears?
I am looking forward to your reply. Thank you a lot in advance.

**Comment by AndyBunn** [comment]
If the spline fits are negative from detrend series then detrend.series (called by detrend) will use the mean instead. I suggest using this online app to see the individual fits to help you visualize the process.

https://andybunn.shinyapps.io/iDetrend/



From: muxi1995 ***@***.***>
Date: Wednesday, September 7, 2022 at 6:07 AM
To: AndyBunn/dplR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AndyBunn/dplR] What is the warnings meaning when we detrend rwl in dplR (Issue #14)

Dear Professor,
when I use the function of 'detrend' in 'dplR' package to detrend the trend of tree ring width I received a warning as follows:
'In (function (y, y.name = "", make.plot = TRUE, method = c("Spline", ... :
In raw series YR338W: Linear fit (backup of method=='ModNegExp') is not all positive.
Proceed with caution.
ARSTAN would tell you to plot that dirty dog at this point."
But when did the detrending process by using "Spline" for another rwl file I received a warning as the following:
' In (function (y, y.name = "", make.plot = TRUE, method = c("Spline", ... :
In raw series 93-59: Fits from method=='Spline' are not all positive.
Series will be detrended with method=='Mean'.
This might not be what you want.
ARSTAN would tell you to plot that dirty dog at this point.
Proceed with caution. '
The second time the warnings said that ' Series will be detrended with method=='Mean'. While it did not appear at the first time. So I want to learn how it is processed the first time. I also read the source code of 'detrend'. But I am not sure whether it was also detrended with the method of 'Mean', except for "Ar". If I used the method of 'Ar' how does it process when the warning appears?
I am looking forward to your reply. Thank you a lot in advance.

**Comment by muxi1995** [comment]
Dear Professor,
   Thank you very much for your reply. I will have a try.



> If the spline fits are negative from detrend series then detrend.series (called by detrend) will use the mean instead. I suggest using this online app to see the individual fits to help you visualize the process. https://andybunn.shinyapps.io/iDetrend/ From: muxi1995 ***@***.***> Date: Wednesday, September 7, 2022 at 6:07 AM To: AndyBunn/dplR ***@***.***> Cc: Subscribed ***@***.***> Subject: [AndyBunn/dplR] What is the warnings meaning when we detrend rwl in dplR (Issue #14) Dear Professor, when I use the function of 'detrend' in 'dplR' package to detrend the trend of tree ring width I received a warning as follows: 'In (function (y, y.name = "", make.plot = TRUE, method = c("Spline", ... : In raw series YR338W: Linear fit (backup of method=='ModNegExp') is not all positive. Proceed with caution. ARSTAN would tell you to plot that dirty dog at this point." But when did the detrending process by using "Spline" for another rwl file I received a warning as the following: ' In (function (y, y.name = "", make.plot = TRUE, method = c("Spline", ... : In raw series 93-59: Fits from method=='Spline' are not all positive. Series will be detrended with method=='Mean'. This might not be what you want. ARSTAN would tell you to plot that dirty dog at this point. Proceed with caution. ' The second time the warnings said that ' Series will be detrended with method=='Mean'. While it did not appear at the first time. So I want to learn how it is processed the first time. I also read the source code of 'detrend'. But I am not sure whether it was also detrended with the method of 'Mean', except for "Ar". If I used the method of 'Ar' how does it process when the warning appears? I am looking forward to your reply. Thank you a lot in advance. — Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAndyBunn%2FdplR%2Fissues%2F14&data=05%7C01%7Cbunna%40wwu.edu%7C9cdc3ee4cc204eedf43408da90d1e39f%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637981528411374281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hi6Hjy0uGZUfJ89eh4iu%2FsL%2FM8LF5EkGhWMpQdYkWZU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC7UCXMH6RJJXGLPEUUHNUDV5CHQHANCNFSM6AAAAAAQGYDQME&data=05%7C01%7Cbunna%40wwu.edu%7C9cdc3ee4cc204eedf43408da90d1e39f%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637981528411374281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l9ehjjS%2FQKgGrdg0g7KoDxqh8HQLlVH%2FjYaDdIfbGlI%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
