### ISSUE TITLE
chron.stabilized not producing output of class crn

### ISSUE THREAD

**Issue by istvan60** [OpenDendro/dplR#18]
Dear Andy!

I ran into what I think is a bug. The `chron()` run on the detrended `Bakta.rwl` works fine and produces an output of crn class, but the `chron.stabilized()` does not. The structure of the two outputs is the same, there is just a difference in class, so I cannot produce the `crn.plot()`. 

![kép](https://user-images.githubusercontent.com/20128185/220577333-8ac70206-977a-4fa1-8e9e-619e49da532f.png)

Could you please take a look at it?
Please find the .rwl data attached

```
Bakta= read.rwl("Bakta.rwl")

outputGHP_std=detrend(rwl=Bakta, make.plot = T, method = c("Spline"),nyrs = 100, f = 0.5, 
                      pos.slope = FALSE, verbose = T, return.info = F, difference = T)


outputGHP_std_chron_stab<-chron.stabilized(outputGHP_std, winLength=51, biweight = TRUE, running.rbar = F)
outputGHP_std_chron_simple<-chron(outputGHP_std)

crn.plot(outputGHP_std_chron_stab)
crn.plot(outputGHP_std_chron_simple)
```
[Bakta.zip](https://github.com/AndyBunn/dplR/files/10801946/Bakta.zip)

Thank you very much!

**Comment by istvan60** [comment]
It seems that 

`class(outputGHP_std_chron_stab) <- c("crn", "data.frame")`

does the trick, however, I had to do this manually and this line seems to be missing from the function.

**Comment by AndyBunn** [comment]
Great. I'm adding that class addition to the function in the dev version. Appreciate the spot.
