### ISSUE TITLE
two-third spline

### ISSUE THREAD

**Issue by sklesse** [OpenDendro/dplR#7]
Hi Andy et al. 

In my recent paper (https://www.sciencedirect.com/science/article/pii/S1125786520301259) I take issue with the application of the two-third spline and that I do not think it is a good default setting within dplR.

I would suggest setting the default spline to a sort of high-pass filter preset of ~30 years, as this kind of application is the most widely used. `nyrs` could still be set to "-n", where n is the n% spline as specified in ARSTAN. In addition, I could envision an implementation of a dataset-wide MSL-based two-third spline `nyrs="MSL"` as another variant to include.

Cheers,
Stefan

**Comment by AndyBunn** [comment]
Hey @sklesse 

After some tests and consideration we agree with your suggestions. We will change the default to 32 yrs to match COFECHA. And add a warning if series length is < nyrs. That's something good for users to know. I'll do that today.
